M48
; DRILL file {KiCad (6.0.7)} date Sun Aug 14 18:42:16 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-14T18:42:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X6.4826Y-4.7527
X6.4826Y-4.8527
X6.4826Y-4.9527
X6.4826Y-5.0527
X6.4826Y-5.1527
T2
X5.65Y-5.175
T0
M30
